export const politicalViews = [
    "Aksiyon",
    "Komedi",
    "Bilim Kurgu",
    "Macera",
    "Dram",
    "Romantik",
    "Gerilim",
    "Korku",
    "Fantastik",
    "Animasyon",
    "Belgesel",
    "Müzikal",
    "Suç",
    "Psikolojik Gerilim",
    "Savaş",
    "Western",
    "Aile",
    "Tarih",
    "Spor",
    "Kara Mizah"
];
